### ISSUE TITLE
missing transactions when importing private key

### ISSUE THREAD

**Issue by heliorosa** [creditbit/creditbit#1]
From what i manage to understand from the code, this happens when a wallet is created and a key is imported (using the debug console).

When the wallet is created the nTimeFirstKey variable is set here: https://github.com/creditbit/creditbit/blob/master/src/wallet.cpp#L53 and this if statement https://github.com/creditbit/creditbit/blob/master/src/wallet.cpp#L852 will skip blocks with transaction to that key.

Commenting that if statement works just fine. Maybe adding a fullScan bool to the function declaration would be useful to give more control over when to scan then entire blockchain ?

**Comment by creditbit** [comment]
Can you try [Version v1.3.0.0](https://github.com/creditbit/creditbit/tree/v1.3.0.0)? feel free to pull request any other changes.

your contribution is really appreciated, Thank you.

**Comment by heliorosa** [comment]
v1.3.0.0 works fine. thanks
