### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by bumbar1** [creditbit/creditbit#2]
There's a couple of problems when building with `makefile.unix`:
- it doesn't create `obj` and `obj/zerocoin` directories
- in `src/leveldb/`, script `build_detect_platform` needs execute permissions (`chmod +x`)

**Comment by creditbit** [comment]
Already fixed in https://github.com/creditbit/creditbit/tree/v1.3.0.0 with few other bugs fixed, you should checkout that version when cloning.

**Comment by bumbar1** [comment]
Thanks for the prompt reply. It built just fine with v1.3.0.0. Maybe it was mentioned somewhere, but I must've missed it.
